ekf_filter_node:
  ros__parameters:
    # 1. 시스템 기본 주기 설정
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    # 2. 좌표계(TF) 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    publish_tf: true

    # 3. [입력 1] 바퀴 엔코더 오돔 설정
    odom0: /odom
    odom0_config: [true,  true,  false,  # 위치 (X, Y 사용 / Z 무시)
                   false, false, false,  # Roll, Pitch, Yaw 미사용 (IMU에게 맡김)
                   true,  true,  false,  # 선속도 (X, Y 속도 사용)
                   false, false, false,  # 각속도 (무시)
                   false, false, false]  # 선가속도 (무시)
    odom0_queue_size: 10

    # 4. [입력 2] IMU 센서 설정
    imu0: /imu
    imu0_config: [false, false, false,  # 위치 (IMU는 위치 측정 불가)
                  false, false, false,  # Roll, Pitch, Yaw (절대 각도 대신 회전 속도 사용)
                  false, false, false,  # 선속도 (측정 불가)
                  false, false, true,   # Z축 각속도 (Yaw 회전속도 감지)
                  true,  false, false]  # X축 선가속도 (멈춤/감속 감지)
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true # 중력 가속도 성분 제거

    # 5. 제어 명령(cmd_vel) 피드백 비활성화
    use_control: false


#   X,     Y,     Z,        [1~3]  3차원 위치 (Position)
#   Roll,  Pitch, Yaw,      [4~6]  3차원 자세 각도 (Orientation)
#   X_vel, Y_vel, Z_vel,    [7~9]  3차원 선속도 (Linear Velocity)
#   R_vel, P_vel, Y_vel,    [10~12] 3차원 각속도 (Angular Velocity)
#   X_acc, Y_acc, Z_acc     [13~15] 3차원 선가속도 (Linear Acceleration)